# Generated by Django 3.2.9 on 2021-11-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_departamento', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('descripcion', models.TextField()),
                ('tipo_doc', models.IntegerField(choices=[[0, 'CC'], [1, 'TI'], [2, 'RC'], [3, 'Otro']])),
                ('antecedentes', models.TextField()),
                ('tipo_paciente', models.IntegerField(choices=[[0, 'Nuevo'], [1, 'Habitual']])),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_sala', models.IntegerField(choices=[[0, 'Privada'], [1, 'Publica'], [2, 'Especial']])),
                ('cant_pacientes', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('edad', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.departamento')),
            ],
        ),
    ]
